### ISSUE TITLE
cdat-lite incompatible with numpy>=1.9

### ISSUE THREAD

**Issue by aidanheerdegen** [ScottWales/conda-envs#4]
https://github.com/cedadev/cdat_lite/issues/2

**Comment by aidanheerdegen** [comment]
Cleanest option is to remove `cdat-lite` from `analysis27`. It is not compatible with `python3`, so is likely on path to a slow death in any case.

If this is mission critical for some people we could

1. Downgrade `numpy` to v1.8 and see what breaks
2. Make a separate environment with `numpy==1.8` and `cdat-lite`
3. Keep `cdat-lite` in `analysis27` and make an `exception.yml` file and list `ncml.py` as not to be tested

**Comment by aidanheerdegen** [comment]
Attempting to use `numpy=1.8` in `analysis27` leads to the following errors:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - datashader -> numba >=0.24.0 -> llvmlite 0.15.*
  - datashader -> numba >=0.24.0 -> numpy 1.11*
  - numpy 1.8*
```

**Comment by ScottWales** [comment]
I would say at least for the present time `cdat-lite` is a hard requirement - it was used for a lot of CMIP5 processing.

**Comment by aidanheerdegen** [comment]
Consensus is to retain `cdat-lite` but mark the `ncml.py` module as known broken (don't test it).

I've done this, but can't commit until one more package is fixed.

**Comment by aidanheerdegen** [comment]
Fixed

https://github.com/ScottWales/conda-envs/commit/fd879189210844142ce67d1a1d38ca37463433c4
